image:
  repository: dixhap/backend
  tag: latest

service:
  port: 8080

serviceAccount:
  create: true

frontend:
  image:
    repository: dixhap/frontend
    tag: latest

database:
  image:
    repository: dixhap/database
    tag: latest

ingress:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1